#!/usr/bin/env bash
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$PROJECT_DIR/.env"
ENV_EXAMPLE="$PROJECT_DIR/.env.example"

prompt_with_default() {
  local label="$1"
  local default_value="$2"
  local value

  if [[ -n "$default_value" ]]; then
    read -r -p "$label [$default_value]: " value
    printf '%s' "${value:-$default_value}"
  else
    read -r -p "$label: " value
    printf '%s' "$value"
  fi
}

prompt_secret() {
  local label="$1"
  local value

  read -r -s -p "$label: " value
  printf '\n' >&2
  printf '%s' "$value"
}

write_env() {
  local model="$1"
  local api_key="$2"
  local base_url="$3"
  local port="$4"

  cat > "$ENV_FILE" <<EOF
# Generated by setup.sh. Do not commit this file.
ENHANCE_MODEL=$model
ENHANCE_API_KEY=$api_key
ENHANCE_BASE_URL=$base_url
REWRITER_PORT=$port
EOF
}

main() {
  printf '%s\n' "FuckAIGC local setup"
  printf '%s\n' "===================="

  if ! command -v python3 >/dev/null 2>&1 && ! command -v python >/dev/null 2>&1; then
    printf '%s\n' "Python 3.10+ is required, but no python executable was found." >&2
    exit 1
  fi

  local python_cmd="python3"
  if ! command -v python3 >/dev/null 2>&1; then
    python_cmd="python"
  fi

  "$python_cmd" - <<'PY'
import sys
if sys.version_info < (3, 10):
    raise SystemExit("Python 3.10+ is required.")
PY

  if [[ -f "$ENV_FILE" ]]; then
    printf '%s\n' ".env already exists."
    read -r -p "Overwrite it? [y/N]: " overwrite
    case "$overwrite" in
      y|Y|yes|YES) ;;
      *)
        printf '%s\n' "Keeping existing .env."
        ;;
    esac
    if [[ ! "$overwrite" =~ ^([yY]|yes|YES)$ ]]; then
      read -r -p "Start the local server now? [y/N]: " start_existing
      if [[ "$start_existing" =~ ^([yY]|yes|YES)$ ]]; then
        cd "$PROJECT_DIR"
        exec "$python_cmd" app.py
      fi
      printf '%s\n' "Setup finished. Run: $python_cmd app.py"
      exit 0
    fi
  elif [[ -f "$ENV_EXAMPLE" ]]; then
    printf '%s\n' "Using .env.example as the configuration template."
  fi

  local model
  local base_url
  local api_key
  local port
  model="$(prompt_with_default "Model" "gemini-2.5-pro")"
  base_url="$(prompt_with_default "Base URL" "https://generativelanguage.googleapis.com/v1beta/openai")"
  api_key="$(prompt_secret "API Key")"
  port="$(prompt_with_default "Local port" "7860")"

  if [[ -z "$api_key" ]]; then
    printf '%s\n' "API Key cannot be empty." >&2
    exit 1
  fi

  write_env "$model" "$api_key" "$base_url" "$port"
  chmod 600 "$ENV_FILE"

  printf '%s\n' "Configuration written to .env."
  printf '%s\n' "Open http://127.0.0.1:$port after starting the server."

  read -r -p "Start the local server now? [y/N]: " start_now
  if [[ "$start_now" =~ ^([yY]|yes|YES)$ ]]; then
    cd "$PROJECT_DIR"
    exec "$python_cmd" app.py
  fi

  printf '%s\n' "Setup finished. Run: $python_cmd app.py"
}

main "$@"
